[project]
name = "apravo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "itsdangerous>=2.2.0",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.45",
]
